### 00. PyTorch Fundamentals
Resource notebook: https://www.learnpytorch.io/00_pytorch_fundamentals/

If you have a question: https://github.com/mrdbourke/pytorch-deep-learning/discussions


In [25]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.11.0+cpu


In [26]:
!nvidia-smi

/bin/bash: line 1: nvidia-smi: command not found


## Introduction to Tensors

### Creating tensors 

PyTorch tensors are created using `torch.Tensor()` = https://pytorch.org/docs/
stable/tensors.html


In [27]:
# scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [28]:
scalar.ndim

0

In [29]:
# get tensor back as python number
scalar.item()

7

In [30]:
# Vector
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [31]:
vector.ndim

1

In [32]:
vector.shape

torch.Size([2])

In [33]:
# Matrix
MATRIX = torch.tensor([[7, 8],
                       [9, 10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [34]:
MATRIX.ndim

2

In [35]:
MATRIX[1]

tensor([ 9, 10])

In [36]:
MATRIX.shape

torch.Size([2, 2])

In [37]:
# TENSOR
TENSOR = torch.tensor([[[1, 2, 3],
                        [3, 6, 9],
                        [2, 4, 5]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [38]:
TENSOR.ndim

3

In [39]:
TENSOR.shape

torch.Size([1, 3, 3])

In [40]:
TENSOR[0]

tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 4, 5]])

### Random tensors

Why random tensors?

Random tensors are important because the way many neural networks learn is that they start with tensors full of random numbers and then
adjust those random numbers to better represent the data.

Start with random numbers -> look at data -> update random numbers -> look at data -> update random numbers

In [ ]:
# Create a random tensor of size (3, 4)
random_tensor = torch.rand(3, 4)
random_tensor

tensor([[0.6271, 0.2012, 0.5089, 0.8499],
        [0.8663, 0.2966, 0.2357, 0.9099],
        [0.1321, 0.1358, 0.2045, 0.8894]])

In [53]:
# Create a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size=(224, 224, 3)) # height, width, color channels
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

In [54]:
# create a tensor of all ones
ones = torch.ones(3, 4)
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [52]:
ones.dtype

torch.float32

### Creating a range of tensors and tensors-like

In [43]:
torch.rand(3,3)

tensor([[0.5981, 0.6644, 0.8254],
        [0.1576, 0.6260, 0.5184],
        [0.4960, 0.7319, 0.9547]])

### Zeros and Ones

In [44]:
# create a tensor of all zeros
zeros = torch.zeros(3, 4)
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [45]:
# create a tensor of all ones
ones = torch.ones(3, 4)
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [46]:
ones.dtype

torch.float32

In [47]:
random_tensor.dtype

torch.float32